version: '3.8'

services:
  # Primary PostgreSQL Database (Write)
  db-primary:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '54322:5432'
    volumes:
      - db-primary-data:/var/lib/postgresql/data
      - ./psql/primary:/docker-entrypoint-initdb.d
    networks:
      - backend
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=2
      -c max_replication_slots=2
      -c hot_standby=on
      -c listen_addresses='*'
      -c max_connections=100
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Secondary PostgreSQL Database (Read only)
  db-secondary:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '54332:5432'
    volumes:
      - db-secondary-data:/var/lib/postgresql/data
    networks:
      - backend
    user: postgres
    command: >
      bash -c "
      until pg_isready -h db-primary -p 5432 -U postgres; do sleep 1; done &&
      rm -rf /var/lib/postgresql/data/* &&
      pg_basebackup -h db-primary -p 5432 -U postgres -D /var/lib/postgresql/data -Fp -Xs -P -R &&
      chmod 700 /var/lib/postgresql/data &&
      echo \"primary_conninfo = 'host=db-primary port=5432 user=postgres password=postgres application_name=db_secondary'\" >> /var/lib/postgresql/data/postgresql.auto.conf &&
      touch /var/lib/postgresql/data/standby.signal &&
      postgres"
    depends_on:
      db-primary:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # HAProxy Load Balancer
  haproxy:
    image: haproxy:latest
    ports:
      - '5050:5000' # Main PostgreSQL proxy port
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - backend
    depends_on:
      db-primary:
        condition: service_healthy
      db-secondary:
        condition: service_healthy
    restart: always

  # Redis (optional for caching, session management, etc.)
  redis:
    image: redis:latest
    networks:
      - backend
    ports:
      - '6379:6379'

networks:
  backend:
    driver: bridge

volumes:
  db-primary-data:
    driver: local
  db-secondary-data:
    driver: local
